/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculatorusingjava;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
/**
 *
 * @author Hasheem
 */
public class Calculator extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form Calculator
     */
    
    private static String str;
   private static boolean clear = false;
    
    public Calculator() {
        initComponents();
        btn0.addActionListener(this);
        btn1.addActionListener(this);
        btn2.addActionListener(this);
        btn3.addActionListener(this);
        btn4.addActionListener(this);
        btn5.addActionListener(this);
        btn6.addActionListener(this);
        btn7.addActionListener(this);
        btn8.addActionListener(this);
        btn9.addActionListener(this);
        equalbtn.addActionListener(this);
        clrbtn.addActionListener(this);
        plusbtn.addActionListener(this);
        mulbtn.addActionListener(this);
        minusbtn.addActionListener(this);
        divbtn.addActionListener(this);
         Seticon();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        input = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        plusbtn = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        minusbtn = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        mulbtn = new javax.swing.JButton();
        divbtn = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        clrbtn = new javax.swing.JButton();
        equalbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(200, 150));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        input.setBackground(new java.awt.Color(243, 255, 255));
        input.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        input.setForeground(new java.awt.Color(0, 102, 102));
        input.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        input.setText("0");
        input.setBorder(null);
        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setAlignmentX(0.0F);
        jPanel3.setAlignmentY(0.0F);
        jPanel3.setLayout(new java.awt.GridLayout(4, 4, 2, 2));

        btn1.setBackground(new java.awt.Color(239, 249, 255));
        btn1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn1.setForeground(new java.awt.Color(0, 102, 102));
        btn1.setText("1");
        btn1.setBorder(null);
        jPanel3.add(btn1);

        btn2.setBackground(new java.awt.Color(239, 249, 255));
        btn2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn2.setForeground(new java.awt.Color(0, 102, 102));
        btn2.setText("2");
        btn2.setBorder(null);
        jPanel3.add(btn2);

        btn3.setBackground(new java.awt.Color(239, 249, 255));
        btn3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn3.setForeground(new java.awt.Color(0, 102, 102));
        btn3.setText("3");
        btn3.setBorder(null);
        jPanel3.add(btn3);

        plusbtn.setBackground(new java.awt.Color(239, 249, 255));
        plusbtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        plusbtn.setForeground(new java.awt.Color(0, 102, 102));
        plusbtn.setText("+");
        plusbtn.setBorder(null);
        jPanel3.add(plusbtn);

        btn4.setBackground(new java.awt.Color(239, 249, 255));
        btn4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn4.setForeground(new java.awt.Color(0, 102, 102));
        btn4.setText("4");
        btn4.setBorder(null);
        jPanel3.add(btn4);

        btn5.setBackground(new java.awt.Color(239, 249, 255));
        btn5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn5.setForeground(new java.awt.Color(0, 102, 102));
        btn5.setText("5");
        btn5.setBorder(null);
        jPanel3.add(btn5);

        btn6.setBackground(new java.awt.Color(239, 249, 255));
        btn6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn6.setForeground(new java.awt.Color(0, 102, 102));
        btn6.setText("6");
        btn6.setBorder(null);
        jPanel3.add(btn6);

        minusbtn.setBackground(new java.awt.Color(239, 249, 255));
        minusbtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        minusbtn.setForeground(new java.awt.Color(0, 102, 102));
        minusbtn.setText("-");
        minusbtn.setBorder(null);
        minusbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusbtnActionPerformed(evt);
            }
        });
        jPanel3.add(minusbtn);

        btn7.setBackground(new java.awt.Color(239, 249, 255));
        btn7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn7.setForeground(new java.awt.Color(0, 102, 102));
        btn7.setText("7");
        btn7.setBorder(null);
        jPanel3.add(btn7);

        btn8.setBackground(new java.awt.Color(239, 249, 255));
        btn8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn8.setForeground(new java.awt.Color(0, 102, 102));
        btn8.setText("8");
        btn8.setBorder(null);
        jPanel3.add(btn8);

        btn9.setBackground(new java.awt.Color(239, 249, 255));
        btn9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn9.setForeground(new java.awt.Color(0, 102, 102));
        btn9.setText("9");
        btn9.setBorder(null);
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel3.add(btn9);

        mulbtn.setBackground(new java.awt.Color(239, 249, 255));
        mulbtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mulbtn.setForeground(new java.awt.Color(0, 102, 102));
        mulbtn.setText("x");
        mulbtn.setBorder(null);
        jPanel3.add(mulbtn);

        divbtn.setBackground(new java.awt.Color(239, 249, 255));
        divbtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        divbtn.setForeground(new java.awt.Color(0, 102, 102));
        divbtn.setText("/");
        divbtn.setBorder(null);
        jPanel3.add(divbtn);

        btn0.setBackground(new java.awt.Color(239, 249, 255));
        btn0.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn0.setForeground(new java.awt.Color(0, 102, 102));
        btn0.setText("0");
        btn0.setBorder(null);
        jPanel3.add(btn0);

        clrbtn.setBackground(new java.awt.Color(239, 249, 255));
        clrbtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        clrbtn.setForeground(new java.awt.Color(0, 102, 102));
        clrbtn.setText("C");
        clrbtn.setBorder(null);
        jPanel3.add(clrbtn);

        equalbtn.setBackground(new java.awt.Color(0, 153, 153));
        equalbtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        equalbtn.setForeground(new java.awt.Color(255, 255, 255));
        equalbtn.setText("=");
        equalbtn.setBorder(null);
        jPanel3.add(equalbtn);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn9ActionPerformed

    private void minusbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minusbtnActionPerformed

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed

    }//GEN-LAST:event_inputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
                
            }
        });
        
        
        str = "";
        
    }
    
    public void Seticon()
    {
        ImageIcon icon = new ImageIcon("calculator.png");
        setIconImage( icon.getImage());
    }
    
    public static boolean operatorduplication()
    {
        if(str.charAt(str.length() - 1) == '+' 
                || str.charAt(str.length() - 1) == '-'
                || str.charAt(str.length() - 1) == '*'
                || str.charAt(str.length() - 1) == '/')
        {
            return false;
        }
        
        return true;
    }
    
    @Override
    public void actionPerformed(ActionEvent e)
    {
        if(clear)
        {
            clear = false;
            input.setText("0");
        }
        
        if (input.getText().equals("0")) 
        {
            input.setText("");
        }
       
        if(e.getSource() == btn0)
        {
            str += "0";
            input.setText(input.getText() + "0");
        }
        else if(e.getSource() == btn1)
        {
            str += "1";
            input.setText(input.getText() + "1");
        }
        else if(e.getSource() == btn2)
        {
            str += "2";
            input.setText(input.getText() + "2");
        }
        else if(e.getSource() == btn3)
        {
            str += "3";
            input.setText(input.getText() + "3");
        }
        else if(e.getSource() == btn4)
        {
            str += "4";
            input.setText(input.getText() + "4");
        }
        else if(e.getSource() == btn5)
        {
            str += "5";
            input.setText(input.getText() + "5");
        }
        else if(e.getSource() == btn6)
        {
            str += "6";
            input.setText(input.getText() + "6");
        }
        else if(e.getSource() == btn7)
        {
            str += "7";
            input.setText(input.getText() + "7");
        }
        else if(e.getSource() == btn8)
        {
            str += "8";
            input.setText(input.getText() + "8");
        }
        else if(e.getSource() == btn9)
        {
            str += "9";
            input.setText(input.getText() + "9");
        }
        else if(e.getSource() == plusbtn)
        {
            if(!str.equals("") && operatorduplication())
            {
                str += "+";
                input.setText(input.getText() + "+");
            }
        }
        else if(e.getSource() == minusbtn)
        {
            if(!str.equals("") && operatorduplication() )
            {
                str += "-";
                input.setText(input.getText() + "-");
            }
        }
        else if(e.getSource() == divbtn)
        {
            if(!str.equals("") && operatorduplication())
            {
                str += "/";
                input.setText(input.getText() + "/");
            }
        }
        else if(e.getSource() == mulbtn)
        {
            if(!str.equals("") && operatorduplication())
            {
                str += "*";
                input.setText(input.getText() + "x");
            }
        }
        else if(e.getSource() == equalbtn)
        {
            StringCalculator obj = new StringCalculator();
            if(obj.ConvertingExpressionIntoArray(str).size() >= 3 && operatorduplication())
            {
                str = obj.StringCalulate(str);
                input.setText(str);
                str = "";
                clear = true;
            }
        }
        else if(e.getSource() == clrbtn)
        {
            str = "";
            input.setText("0");
        }
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton clrbtn;
    private javax.swing.JButton divbtn;
    private javax.swing.JButton equalbtn;
    private javax.swing.JTextField input;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton minusbtn;
    private javax.swing.JButton mulbtn;
    private javax.swing.JButton plusbtn;
    // End of variables declaration//GEN-END:variables
}
